# Generated by Django 5.2.1 on 2025-06-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autores',
        ),
    ]
